### ISSUE TITLE
Attribute names get masked by other attributes

### ISSUE THREAD

**Issue by rmst** [wandb/user-issues#6]
Hi, I really like the new web interface. It fixed so many things :) As we can now use dots in the attribute names I changed my naming scheme a bit. I tried to use dots before and stopped after I noticed that it wasn't working. Back then I named one attribte "agent.lr". In my new scheme that attribute would be called "Agent.lr" however when I try to sort, group or filter with "Agent.lr", only "agent.lr" shows up and I have no way of overriding that. I even tried to delete all old runs that used "agent.lr" but it still shows up as the only option.

**Comment by shawnlewis** [comment]
This is an issue with case-sensitivity. You need to maintain the same case across runs for now.

How did you find this issue repository by the way?

**Comment by rmst** [comment]
Hi, thanks for the answer. I worked around it by creating a new project that doesn't have the lower case attributes. Is there a way to move experiments between projects, btw?

> How did you find this issue repository by the way?

Don't remember exactly but I believe I was told to report issues with the web interface here at some point. Would it be better if I'd use another channel in the future? - /dev/null :P ?

**Comment by shawnlewis** [comment]
There's not currently a way to move experiments, but the request has been coming up more and more so we're actively tracking. We may do something within the next few weeks.

You're welcome to post here! It's just that we haven't had any issues filed here for quite awhile.

Typically people either use Intercom to contact us (the chat bubble at the bottom right of the app), or our newer community forum on Gitter: https://gitter.im/wandb-app/community

**Comment by rmst** [comment]
Great, thanks!

**Comment by rmst** [comment]
Ah, perhaps there could be a quick fix for this issue though: Accepting the exact string that user wrote when enter is pressed instead of automatically selecting one of the autocomplete items or at least allow the user to deselect the autocomplete item by pressing esc or up.

**Comment by rmst** [comment]
In general, are there certain attribute names that should be avoided? Do they have to be below a certain length? When I try to group by "Agent.Model.LastPolicyLayer.__name__" I'm just getting <null> even though the attribute show up on the individual experiments' pages under logs.

**Comment by vanpelt** [comment]
@rmst we treat dots in a special way on the backend.  If you send us nested attributes we allow accessing them via dots, so you can hit weird issues if you have both nested attributes and attribute keys with dots in them.  We're planning a refactor to settle this once and for all.  For now are you able to make everything work by using slashes?

**Comment by rmst** [comment]
Ah okay,  I didn't realize that I could pass nested attributes. That was actually what I was trying to do manually by flattening the dict before I pass it to the wandb api. The slashes seem to work fine now. Perhaps I'm gonna try passing the nested dict directly in the future. Thanks for the response!
