### ISSUE TITLE
Issue with the commandline argument: --config

### ISSUE THREAD

**Issue by tshrjn** [wandb/user-issues#7]
The [config docs](https://docs.wandb.com/docs/config.html) mention using the command line argument `--configs` to load parameters from a configs yaml file.

I do just that using: `wandb --configs config/config.yaml`. But am greeted with the error:
`Error: no such option: --configs`

Also, the command line docs don't seem to mention this uploading of config file feature.

**Comment by vanpelt** [comment]
Hey @tshrjn that only works if you launch your scripts with `wandb run --configs config/config.yaml script_name.py`.  It will always automatically load a file named `config-defaults.yaml` even when running the script with `python script_name.py`.  This config functionality is something we're considering deprecated.  If you type `wandb run --help` from a terminal you'll see the command line docs.
